name: Databricks CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli
          databricks --version

      - name: Deploy to DEV
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
        run: |
          databricks bundle deploy \
            --profile dev \
            --path databricks

  deploy-qa:
    name: Deploy to QA
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli
          databricks --version

      - name: Deploy to QA
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_QA_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_QA_TOKEN }}
        run: |
          databricks bundle deploy \
            --profile qa \
            --path databricks

  deploy-prod:
    name: Deploy to PROD
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: productio
