name: Databricks CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        uses: microsoft/install-databricks-cli@v1.0.0

      - name: Push Notebooks to Dev Workspace
        uses: microsoft/databricks-import-notebook@v1.0.0 
        with:
          databricks-host: ${{ secrets.DATABRICKS_HOST }}
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          local-path: ./databricks
          remote-path: /dev_deploy
