name: Deploy to Databricks with OIDC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AAD access token for Databricks
        id: get-token
        run: |
          access_token=$(az account get-access-token --resource https://databricks.azure.net --query accessToken -o tsv)
          echo "DATABRICKS_AAD_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Deploy to Databricks
        uses: microsoft/databricks-import-notebook@v1.0.0 
        with:
          databricks-host: ${{ secrets.DATABRICKS_HOST }}
          databricks-token: ${{ env.DATABRICKS_AAD_TOKEN }}
          local-path: ./databricks
          remote-path: /dev_OIDC_deploy
